import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Container,Col,Row } from "react-bootstrap";
import NavBar from "./ui/navigation/nav";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Container fluid className="p-0" id="main-container">
         <Row id="header " className="p-0 m-0 fixed-top">
          <NavBar/>
         </Row> 
         <Row id="body" className="m-0">
         {children}
         </Row> 
         
        </Container>
        
      </body>
    </html>
  );
}
